[workspace]
members = [
    "crates/flarrow-api",
    "crates/derive/flarrow-api-derive",
    "crates/flarrow-builtins",
    "crates/flarrow-layout",
    "crates/flarrow-message",
    "crates/derive/flarrow-message-derive",
    "crates/flarrow-runtime",
    "crates/flarrow-flows",
    "crates/flarrow-runtime-core",
    "crates/plugins/flarrow-url-scheme",
    "crates/plugins/flarrow-file-ext",
]
resolver = "3"

[workspace.package]
authors = ["Enzo Le Van <dev@enzo-le-van.fr>"]
description = "flarrow (flow + arrow) is a rust runtime/framework for building dataflow applications."
edition = "2024"
homepage = "https://github.com/flarrow/flarrow-rs"
keywords = []
readme = "README.md"
rust-version = "1.85"
categories = []
documentation = "https://github.com/flarrow/flarrow-rs"
license = "Apache-2.0"
repository = "https://github.com/flarrow/flarrow-rs"
version = "0.3.0"

[workspace.dependencies]
eyre = { version = "0.6", default-features = false, features = [
    "auto-install",
] }

url = { version = "2", default-features = false, features = ["std"] }
uhlc = { version = "0.8", default-features = false }

serde_yml = "0.0.12"

libloading = "0.8"

proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

arrow-data = "54"
arrow-schema = "54"
arrow-array = "54"
arrow-buffer = "54"

uuid = { version = "1", default-features = false, features = ["v4", "v3"] }

tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
    "signal",
    "fs",
] }

tracing = "0.1"
tracing-subscriber = "0.3"

flarrow-layout = { version = "0.3.0", path = "crates/flarrow-layout" }

flarrow-message = { version = "0.3.0", path = "crates/flarrow-message" }
flarrow-message-derive = { version = "0.3.0", path = "crates/derive/flarrow-message-derive" }

flarrow-api = { version = "0.3.0", path = "crates/flarrow-api" }
flarrow-api-derive = { version = "0.3.0", path = "crates/derive/flarrow-api-derive" }

flarrow-builtins = { version = "0.3.0", path = "crates/flarrow-builtins" }

flarrow-flows = { version = "0.3.0", path = "crates/flarrow-flows" }

flarrow-runtime-core = { version = "0.3.0", path = "crates/flarrow-runtime-core" }

flarrow-file-ext = { version = "0.3.0", path = "crates/plugins/flarrow-file-ext" }
flarrow-url-scheme = { version = "0.3.0", path = "crates/plugins/flarrow-url-scheme" }

flarrow-runtime = { version = "0.3.0", path = "crates/flarrow-runtime" }


[workspace.metadata.release]
rate-limit.new-packages = 10
