[workspace]
members = [
    "crates/flarrow-api",
    "crates/flarrow-api-derive",
    "crates/flarrow-builtins",
    "crates/flarrow-layout",
    "crates/flarrow-message",
    "crates/flarrow-message-derive",
    "crates/flarrow-message-python",
    "crates/flarrow-runtime",
    "crates/flarrow-runtime-plan",
    "crates/flarrow-url",
]
resolver = "3"

[workspace.package]
authors = ["Enzo Le Van <dev@enzo-le-van.fr>"]
description = ""
edition = "2024"
homepage = ""
keywords = []
readme = "README.md"
rust-version = "1.85"
categories = []
documentation = "https://github.com/"
license = "Apache-2.0"
repository = "https://github.com/"
version = "0.1.0"

[workspace.dependencies]
url = "2"
pyo3 = "0.23"
serde = "1.0"
eyre = "0.6"
uhlc = "0.8"
serde_yml = "0.0.12"
libloading = "0.8"

uuid = { version = "1", features = ["v4", "v3"] }
arrow = { version = "54", default-features = false }
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
    "signal",
    "fs",
] }
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "charset",
    "http2",
    "macos-system-configuration",
] }

flarrow-layout = { version = "0.1.0", path = "crates/flarrow-layout" }
flarrow-api = { version = "0.1.0", path = "crates/flarrow-api" }
flarrow-api-derive = { version = "0.1.0", path = "crates/flarrow-api-derive" }
flarrow-runtime = { version = "0.1.0", path = "crates/flarrow-runtime" }
flarrow-runtime-plan = { version = "0.1.0", path = "crates/flarrow-runtime-plan" }
flarrow-builtins = { version = "0.1.0", path = "crates/flarrow-builtins" }
flarrow-url = { version = "0.1.0", path = "crates/flarrow-url" }

flarrow-message = { version = "0.1.0", path = "crates/flarrow-message" }
flarrow-message-derive = { version = "0.1.0", path = "crates/flarrow-message-derive" }
flarrow-message-python = { version = "0.1.0", path = "crates/flarrow-message-python" }
