[workspace]
members = [
    "crates/flarrow-api",
    "crates/flarrow-api-derive",
    "crates/flarrow-builtins",
    "crates/flarrow-layout",
    "crates/flarrow-message",
    "crates/flarrow-message-derive",
    "crates/flarrow-runtime",
    "crates/flarrow-runtime-plan",
    "crates/flarrow-url",
    "crates/flarrow-url-default",
]
resolver = "3"

[workspace.package]
authors = ["Enzo Le Van <dev@enzo-le-van.fr>"]
description = ""
edition = "2024"
homepage = ""
keywords = []
readme = "README.md"
rust-version = "1.85"
categories = []
documentation = "https://github.com/"
license = "Apache-2.0"
repository = "https://github.com/"
version = "0.1.0"

[workspace.dependencies]
eyre = { version = "0.6", default-features = false, features = [
    "auto-install",
] }

url = { version = "2", default-features = false }
uhlc = { version = "0.8", default-features = false }

serde = "1.0"
serde_yml = "0.0.12"

libloading = "0.8"

proc-macro2 = "1"
quote = "1"
syn = "2"

arrow-data = "54"
arrow-schema = "54"
arrow-array = "54"
arrow-buffer = "54"

uuid = { version = "1", default-features = false, features = ["v4", "v3"] }

tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
    "signal",
    "fs",
] }

flarrow-layout = { version = "0.1.0", path = "crates/flarrow-layout" }
flarrow-api = { version = "0.1.0", path = "crates/flarrow-api" }
flarrow-api-derive = { version = "0.1.0", path = "crates/flarrow-api-derive" }
flarrow-runtime = { version = "0.1.0", path = "crates/flarrow-runtime" }
flarrow-runtime-plan = { version = "0.1.0", path = "crates/flarrow-runtime-plan" }
flarrow-builtins = { version = "0.1.0", path = "crates/flarrow-builtins" }
flarrow-url = { version = "0.1.0", path = "crates/flarrow-url" }
flarrow-url-default = { version = "0.1.0", path = "crates/flarrow-url-default" }

flarrow-message = { version = "0.1.0", path = "crates/flarrow-message" }
flarrow-message-derive = { version = "0.1.0", path = "crates/flarrow-message-derive" }
